### ISSUE TITLE
Cannot serialize hashmap with usize/i32... keys

### ISSUE THREAD

**Issue by indefini** [toml-rs/toml-rs#212]
I tried to serialize a hashmap with usize keys but I got a KeyNotString error.
https://play.rust-lang.org/?gist=1542b7108c652d2679ce2d8d56e9e015&version=stable

toml supports only digits keys, so I wondered if this is just not implemented yet, or if there is a good reason such keys cannot exist?

**Comment by alexcrichton** [comment]
This is currently intentional as TOML-the-format only supports strings as keys, but we could auto-stringify I think which may help!

**Comment by clarcharr** [comment]
serde-json had some workaround for this; maybe you  could see what they do for it?

**Comment by wucke13** [comment]
I also stumbled up on the need to automatically parse an integer from the Key string. What does it take to get this done?

**Comment by abreis** [comment]
I'd also welcome this, though perhaps as an optional feature.

@wucke13 looking at `ser.rs`:
https://github.com/alexcrichton/toml-rs/blob/7a43ac9e9c28afec8414f6d924024f5d33fe8fa2/src/ser.rs#L1372-L1373

I suppose you'd want these primitive methods to return `v.to_string()` instead of `Error::KeyNotString`, and then generically for any type that implements `ToString`. Then on the deserialization side, allow `T: FromStr` for map keys, and call `.parse()` on the .toml string keys.

**Comment by vpzomtrrfrt** [comment]
So the outstanding question is whether this should be an option as opposed to default behaviour?

**Comment by wucke13** [comment]
What would be the argument against making it default? I'm curious as I did not find one on my own :smile:

**Comment by jonasbb** [comment]
The [`serde_with`](https://docs.rs/serde_with/1.6.0/serde_with/guide/index.html#2-a-more-flexible-and-composable-replacement-for-the-with-annotation-called-serde_as-v150) crate can be used to work around that limitation for now:

```rust
use serde_with::{serde_as, DisplayFromStr};
use std::collections::HashMap;

#[serde_as]
#[derive(Debug, Serialize, Deserialize)]
struct X {
    #[serde_as(as = "HashMap<DisplayFromStr, _>")]
    a: HashMap<usize, usize>,
}

let x = X{a: vec![(1,1), (2,2)].into_iter().collect()};
let s = toml::to_string(&x).unwrap();
println!("{}", s);
let x: X = toml::from_str(&s).unwrap();
println!("{:?}", x);
```

**Comment by CuriouslyCurious** [comment]
As the definitive toml parsing library I believe this issue is quite pertinent and important for usability. 

I've bumped into this issue as well and having to finagle in another crate to solve it is not ideal. The suggestion by @abreis sounds like a great simple solution to the problem. One could then implement `ToString` for custom structs and enums and so on to get the desired output.

For user-friendliness I think the stricter `KeyNotString` "feature" should be the one behind a feature flag. Having more descriptive errors about which key is the one that's failing the serialization would also be nice. :P

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
