### ISSUE TITLE
Why can't you encode to any "Write"?

### ISSUE THREAD

**Issue by quadrupleslap** [toml-rs/toml-rs#216]
If i grep for `self.dst` in `ser.rs`, all I can find are `push_str` and `write!` calls, so it looks like any writer should be accepted. Would a pull request be considered?

Edit: Also, this change would mean that a string wouldn't need to be created on every `<toml::Value as fmt::Display>::fmt` call.

**Comment by alexcrichton** [comment]
This is sort of the same as https://github.com/alexcrichton/toml-rs/issues/215 only the reverse, but when originally writing this crate I decided to only serialize to a string rather than to a fallible destination. We could add a convenience wrapper that allocates a string and then writes to a `Write`, though.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
