### ISSUE TITLE
inserting values with [ ]

### ISSUE THREAD

**Issue by jaroslaw-weber** [toml-rs/toml-rs#231]
I was able to insert new key/value pairs to json with [] indexing, but it seems is not possible with toml crate. Would the implementation is difficult? How would I go about adding new information into Value::Table?

```
extern crate toml;
use toml::value::Value as Toml;
use toml::Value;

fn main() {

    let mut toml_obj = "foo = 'bar'".parse::<Value>().unwrap();
    toml_obj["new_key"]=Toml::Boolean(true);
    println!("{:?}", &toml_obj);
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I believe this works in Serde because `IndexMut` returns a reference to `null` if the key isn't otherwise present. Unfortunately TOML doesn't have the same notion of null so the same trick doesn't work for us.

In that sense this won't be easily implementable until we get something like `IndexSet` as a trait in the language :(

**Comment by jaroslaw-weber** [comment]
@alexcrichton  
hey, thanks for response! What would be a way to insert a new value into Value?
It would be great to have 
```
Value::insert(&mut self, key: &str, value: Value)-> Result<(), Error>
```
for modifying the Value. Would it be possible to implement?

**Comment by alexcrichton** [comment]
Certainly! That sounds plausible to me

**Comment by ehuss** [comment]
cc #193 which is similar.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
