### ISSUE TITLE
ValueAfterTable error

### ISSUE THREAD

**Issue by PSeitz** [toml-rs/toml-rs#336]
I created this website using toml-rs and wasm to convert json to toml:
https://pseitz.github.io/toml-to-json-online-converter/

The code is pretty straightforward, but sometimes I get the ValueAfterTable error.
I have no idea how to fix this, since the input is generic. (Reorder the serde_json::Value?) 
```rust
#[wasm_bindgen]
pub fn convert_json_to_toml(input:&str) -> Result<String, JsValue>{
 
    let mut toml = String::new();

    let mut deserializer = Deserializer::from_str(input);
    let mut serializer = Serializer::pretty(&mut toml);
    serde_transcode::transcode(&mut deserializer, &mut serializer).map_err(|err| JsValue::from_str(&err.to_string()))?;
  
    Ok(toml)
}

```

JSON Input:
`{
  "kana": {"ent_seq": "1000000"},
  "kanji": []
}`

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not really certain where this is coming from, but my guess would be the transcoding step. Perhaps parsing to `json::Value` and then serializing that with toml would work?

**Comment by PSeitz** [comment]
That was my first try, but lead to the same issue (but in other cases)

**Comment by alexcrichton** [comment]
Could you gist the error when using `json::Value` to test out locally?

**Comment by PSeitz** [comment]
I create a repo here:
https://github.com/PSeitz/value_after-table

```
fn main() {
    let val: serde_json::Value = serde_json::from_str(r#"{ "kana": {"ent_seq": "1000000"}, "kanji": [] }"#).unwrap();
    toml::ser::to_string_pretty(&val).unwrap();
}
```

**Comment by alexcrichton** [comment]
Ah ok I think I see the issue here. We're attempting to emit `kanji = []` instead of `[[kanji]]`, which is indeed an error. We should automatically switch to `[[kanji]]` though instead. The block that handles this is around here -- https://github.com/alexcrichton/toml-rs/blob/41dd8e674144f208d36790a781011f9ea63e20f1/src/ser.rs#L1003-L1007

**Comment by novacrazy** [comment]
I seem to be encountering a `ValueAfterTable` error when using this schema:

<details>

```rust
use raygon::geometry::{Matrix4x4, Quaternion, Vector3};

/// String or integer ID
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StringlyId {
    I(u64),
    S(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InstanceParent {
    /// Use the parent transform chain with the given asset
    Both { asset: StringlyId, parent: StringlyId },
    /// Instance this asset
    Asset { asset: StringlyId },
    /// Instance another instance
    Parent { parent: StringlyId },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Instance {
    /// ID of this instance so it can be referenced later
    #[serde(default)]
    pub id: Option<StringlyId>,

    #[serde(flatten)]
    pub parent: InstanceParent,

    #[serde(default)]
    pub transform: Option<TransformSettings>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotationSetting {
    Explicit {
        #[serde(default)]
        quaternion: Option<Quaternion>,

        #[serde(default)]
        euler_angles: Option<Vector3>,

        #[serde(default)]
        axis_angle: Option<Vector3>,
    },
    ImplicitEulerAngles(Vector3),
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScaleSetting {
    Uniform(f32),
    NonUniform(Vector3),
}

impl Default for ScaleSetting {
    fn default() -> ScaleSetting {
        ScaleSetting::Uniform(1.0)
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransformSettings {
    Matrix(Matrix4x4),
    Component {
        #[serde(default)]
        translation: Option<Vector3>,

        #[serde(default)]
        rotation: Option<RotationSetting>,

        #[serde(default)]
        scale: Option<ScaleSetting>,
    },
}
```
</details>

with this relevant excerpt from the `.toml` file:

```toml
[[instances]]
id = '2'
parent = '1' # reference instance 1
[instances.transform]
scale = [1.0, 2.0, 3.0, 0.0]
rotation = { quaternion = [0.0, 0.7, 0.0, 0.7] }
```

It parses and deserializes it just fine, but the error occurs when serializing again back to TOML.

**Comment by davidB** [comment]
Any progress ? (I have the issue with 0.5.6, and same use case  toml -> toml::Value -> json::Value -> toml::Value (error ValueAfterTable) with simple case like:

```
                    [foo]
                    bar = { baz = true }
                    hello = "1.2.3"
```

**Comment by PSeitz** [comment]
I tested a fix here: https://github.com/alexcrichton/toml-rs/pull/339/files, which seems to be the wrong place. There were also some parts in the serializer I didn't understand to proceed.

**Comment by zohnannor** [comment]
I think this happens just because of the fact that keys of values in JSON map are iterated in alphabetical order?

This helped in my situation (converting JSON to TOML):

```toml
[dependencies.serde_json]
version = "1.0.79"
features = ["preserve_order"]

[dependencies.toml]
version = "0.5.8"
features = ["preserve_order"]
```

That way deserializers use [`Indexmap`](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html) instead of [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html).  
However, if you manually put JSON array before other keys, it will fail. The order matters and I don't like this solution much.

P.S. In the example by @jonhoo, it is even weirder: the error happens inconsistently because of the way iteration over the `HashMap` keys works, so sometimes you'd see the error and sometimes don't.

The proper fix for this would be to (recursively) "sort" the JSON before passing to TOML serializer, giving the "value" keys before the "table" keys.

**Comment by turbinenreiter** [comment]
I'd like to add an example that leads to ValueAfterTable error, although I don't (knowingly) use tables (HashMaps, right?): https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c2d4d30fb7dcbc3a8085b0f7ea42c00c

I'm not sure if this in an instance of the same bug or user error.

**Comment by zohnannor** [comment]
@turbinenreiter
I believe, the "table" here is your `Args` struct and the `value` is the `statements` field. Simplest fix: place `args` field at the bottom in the definition of `Method`.

```rust
#[derive(Debug, Serialize)]
pub struct Method {
    name: String,
    ret: String,
    statements: Vec<Statement>,
    args: Vec<Arg>, // <- "table" after "values"
}
```

Produces:

```toml
name = 'test'

[[methods]]
name = 'testo'
ret = 'suc'
statements = ['Use']

[[methods.args]]
name = 'i'
pbtype = 'int'
```

As you can see, `[[methods.args]]` is a table and it is placed after `ret` and `statements` fields, as opposed to before, when it tried serializing it as:

```toml
name = 'test'

[[methods]]
name = 'testo'

[methods.args]
name = 'i'
pbtype = 'int'

statements = ['Use']
ret = 'suc'
```

which is obviously not correct.

And yeah, I consider this a bug. Serializer should preemptively "sort" the fields so that *table-like* structures would appear after *value* ones. Alternatively, it could serialize some fields as TOML's ["inline tables"](https://toml.io/en/v1.0.0#inline-table) like this:

```toml
name = 'test'

[[methods]]
name = 'testo'
args = { name = 'i', pbtype = 'int' }
statements = ['Use']
ret = 'suc'
```

and that is more readable and concise in my opinion.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
